apiVersion: v1
kind: Service
metadata:
  name: openfaas-gateway
  namespace: openfaas
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30080
  selector:
    app: gateway